### PR TITLE
Feat: Added Pricing Table code blocks.

### PR DESCRIPTION
**Pull request by pranavvp10**
Added two pricing table code blocks into Pricing Table category.

### CODE REVIEW

**Comment by VaibhavSaini19** [comment]
@pranavvp10 The cards have inconsistent padding and somewhat unnecessary borders as well, which ruins the looks a little bit. Can you fix that please?  Maybe go through some more dribble / behance shots

**Comment by pranavvp10** [comment]
@VaibhavSaini19  sure I will make changes to it.

**Comment by VaibhavSaini19** [comment]
@pranavvp10 You went over with a little too much padding on the x-axis, the cards are larger than expected now. And also, the "premium" text looks like it doesn't have room to breathe. If you could fix that, it would be great. While you are at it, please also change the title of the category to just "PRICING" instead of "PRICINGTABLE", as it would contain both pricing tables and pricing cards as well

**Comment by VaibhavSaini19** [comment]
Check out the pricing tabs under `https://mertjf.github.io/tailblocks/`. If you can create something of that sort, it would be excellent

**Comment by VaibhavSaini19** [comment]
@pranavvp10 These do look much better. However, the cards don't stay consistent across tablet devices due to flex-wrap (as they don't have fixed width). I suggest you change it back to using row-cols-1, row-cols-2 etc (like you did earlier). Also, add ".btn-block" to all the buttons and add the "features" lines (with tick-marks) from pricing_2 to pricing_1 as well

**Comment by VaibhavSaini19** [comment]
@pranavvp10 Can you make the following changes please:
- Add row-cols-* for all the viewports, default 1, 2 for sm, 3 for md and 4 for xl
- Remove horizontal padding in buttons in pricing_2, so that it aligns with the rest of the text above it (make it just like it is in pricing_1)
- Add gutter class to row so that there is gap between the cards vertically in devices that smaller than desktop

**Comment by VaibhavSaini19** [comment]
Looks good @pranavvp10. Will merge soon after a final check

**Comment by pranavvp10** [comment]
Thanks :relaxed:

**Review by VaibhavSaini19 — CHANGES_REQUESTED** [review]
@pranavvp10 Just reduce the gutter size to 2. And I found a lot of classes like "flex", "h-full", "hover:bg-grey" etc. in the code that are not Bootstrap classes. Remove them as they might create confusion for fellow developers. That would be all

**Review by VaibhavSaini19 — APPROVED** [review]

**Review by VaibhavSaini19 — APPROVED** [review]

**Comment by pranavvp10** [comment]
Thanks @VaibhavSaini19

**Pull request merged**
