### PR TITLE
Added svg thumbnails for hero blocks

### PR DESCRIPTION
**Pull request by GaganSingh5**
## What does this PR do?

Added two svg files for the thumbnail of hero block

### Have you read the [Contributing Guidelines](https://github.com/VaibhavSaini19/BootBlox/blob/master/CONTRIBUTING.md)?

yes

## SVG added are

hero1

hero_2_thumb

### CODE REVIEW

**Review by VaibhavSaini19 — CHANGES_REQUESTED** [review]
@GaganSingh5 can you scale down the thickness and size of the lines representing text? As you can see in the block, the CTA buttons and input fields have same height as that of text. Also the buttons are supposed to be just slightly rounded, instead of pill shaped. 
Alse, Have you given the background a gray-ish color? If so, make it white please

P.S. Can you please merge your branch to your fork master and make a PR from there please? (We are currently facing an issue with one of the GitHub Actions). If not, no worries, we are working to fix the issue ASAP anyway

**Comment by GaganSingh5** [comment]
The requested changes look like

Untitled

**Review by VaibhavSaini19 — CHANGES_REQUESTED** [review]
@GaganSingh5 The background is still gray, if I'm not wrong. As asked earlier, need that to be white. And make the black-ish line (heading line) completely black, and the other lines just a little lighter gray

**Comment by VaibhavSaini19** [comment]
@GaganSingh5 we have update our GitHub actions recently. So to pass the CI checks you will need to enable actions in your fork and then make a PR. Please do the needful

**Comment by GaganSingh5** [comment]
Thats how the changes looks

> @GaganSingh5 we have update our GitHub actions recently. So to pass the CI checks you will need to enable actions in your fork and then make a PR. Please do the needful

I enabled actions , now do i have to create a new pull request from the forked repo?

**Comment by GaganSingh5** [comment]
changes look like @VaibhavSaini19 

Untitled

**Comment by VaibhavSaini19** [comment]
@GaganSingh5 yes you need to make a new PR

**Pull request merged**
