### PR TITLE
Feat : Add SEO meta tags

### PR DESCRIPTION
**Pull request by trivedi-vatsal**
## What does this PR do?

To increase the visibility of the page using meta tags.

### Have you read the [Contributing Guidelines](https://github.com/VaibhavSaini19/BootBlox/blob/master/CONTRIBUTING.md)?

Yes i have read

### CODE REVIEW

**Comment by VaibhavSaini19** [comment]
Hi @trivedi-vatsal , thanks for your interest in contributing to the project. You are requested to list the issue that this PR resolves please

**Comment by trivedi-vatsal** [comment]
@VaibhavSaini19 
I went through the list, didn't find any issues related to this. The merge request is quite simple adding some meta tags that will help to rank more in SEO.

**Comment by VaibhavSaini19** [comment]
@trivedi-vatsal I recently updated one of the workflows to fix a bug (that was preventing PRs to pass the `Format` check). To trigger the new checks, you need to close this PR and make a new one anyway. So i request you to do the same, and while you are at it feel free to add the corresponding issue as well

**Comment by t0xic0der** [comment]
> I went through the list, didn't find any issues related to this. The merge request is quite simple adding some meta tags that will help to rank more in SEO.

Please go ahead and create an issue for the PR if there isn't any. The contributors will then discuss if at all the issue requires addressing and then, get into reviewing your pull request.

For your reference @VaibhavSaini19.

**Pull request closed without merging**
