### PR TITLE
Added GitHub Actions and templates for BootBlox

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #15

### CODE REVIEW

**Comment by iamrajiv** [comment]
@t0xic0der @VaibhavSaini19 Please review.

**Review by VaibhavSaini19 — APPROVED** [review]
Looks good to me

**Comment by iamrajiv** [comment]
@VaibhavSaini19 Can you add Hacktoberfest label to the issue and PR like in issue documentation is labelled but the issue is related to the enhancement.

**Review by t0xic0der — APPROVED** [review]
Good work with the issue templates and the check pipelines. :smile:

**Comment by t0xic0der** [comment]
> Can you add Hacktoberfest label to the issue and PR like in issue documentation is labelled but the issue is related to the enhancement.

I am not sure what you are trying to say here but I think you are asking if we could label the issue `hacktoberfest`.

If so, we would certainly do what you requested for as a token of appreciation for your contributions made to this repository but you are requested to see the bigger picture here. Please do not make pull requests just for the sake of transient swags but do so for the sake for the permanent positive impact, you could make to the free and open-source software initiative.

Thank you.

**Comment by VaibhavSaini19** [comment]
Merging

**Pull request merged**
