### PR TITLE
Feat: Add pricing icons and logic to display them

### LINKED ISSUE #24: SVG thumbnails for "Pricing" category
## 🚀 Feature

A default thumbnail is being used currently for a code block.
For the **"Pricing"** category, SVG thubmnails that represents the code block preview in an abstract manner (like a skeleton template) would help a user to get an intuition about the template in a glance in the sidebar itself

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Contributing Guidelines](https://github.com/VaibhavSaini19/BootBlox/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

This would enhance the user experience by providing a quick abstract preview of the code block in the sidebar that would reduce the time required to find the desired template. The thumbnail can be designed using any designing tool like Figma, Adobe XD etc.

### PR DESCRIPTION
**Pull request by erinknight242**
## What does this PR do?
Adds icons for the Pricing category

## Test Plan

Opened index.html and viewed sidebar

## Related PRs and Issues

Resolves #24 

### Have you read the [Contributing Guidelines](https://github.com/VaibhavSaini19/BootBlox/blob/master/CONTRIBUTING.md)?
yes

Screen shot of images added:
Screen Shot 2020-10-14 at 9 59 57 PM

### CODE REVIEW

**Review by VaibhavSaini19 — CHANGES_REQUESTED** [review]
@erinknight242 The thumbnails are fine. But, I would request you to follow the naming convention as described in the [CONTRIBUTING.md](https://github.com/VaibhavSaini19/BootBlox/blob/master/CONTRIBUTING.md) . I am aware that the thumbnails don't show up yet since we are using the temporary one as the source for all. I'll create a seperate issue to address this problem so that it shows the correct thumbnail if available, and temporary one otherwise. Until then, revert the changes done in script.js please

**Comment by erinknight242** [comment]
@VaibhavSaini19 PR Updated

**Review by VaibhavSaini19 — APPROVED** [review]
Looks good to me

**Comment by VaibhavSaini19** [comment]
@erinknight242 I am currently facing a minor problem with the GitHub Actions, will merge as soon as it is fixed. Thanks for your contribution, and don't forget to star the repo if you liked it 😀

**Pull request merged**
